apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.metadata.name }}
  name: {{ .Values.metadata.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
    spec:
      containers:
      - image: yossefsameh/bakehouse-app:1
        name: {{ .Values.metadata.name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
